"""
reporter.py — streaming /report command with auto-save to Obsidian vault.

Separate from report.py (which handles /payload, /tools, /explain, /compact)
because the streaming + file-save pattern is distinct enough to warrant its own module.
"""
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from rich.console import Console
from rich.panel import Panel
from rich.rule import Rule
from rich.text import Text

from franki.config import FrankiConfig
from franki.utils.ai import stream_to_terminal

if TYPE_CHECKING:
    from franki.session import Session

GOLD     = "#d4a853"
TEXT_DIM = "#555555"
BORDER   = "#2d2d2d"

_PENTEST_SYS = """\
You are a professional penetration test report writer.
Generate a complete, structured report from the conversation provided.
Use markdown with these exact sections:
# Penetration Test Report
## Executive Summary
## Scope
## Methodology
## Findings
(list each finding as: ### Finding N: <Title> — Severity: Critical/High/Medium/Low/Info)
## Risk Ratings Summary
## Recommendations
## Conclusion
Be specific. Extract real tool names, IPs, ports, and commands from the conversation.
Write in professional report language.\
"""

_SOC_SYS = """\
You are a SOC analyst report writer.
Generate a complete incident response report from the conversation.
Use markdown with these exact sections:
# Incident Response Report
## Incident Summary
## Timeline
## Indicators of Compromise (IOCs)
## MITRE ATT&CK TTPs
## Affected Systems
## Containment Actions Taken
## Recommendations
## Lessons Learned
Extract real IOCs, timestamps, and system names from the conversation.\
"""

_DEFAULT_SYS = """\
Generate a structured session summary report from the conversation.
Use markdown headings. Cover: key findings, decisions made, code produced, commands run, and next steps.
Write in professional technical language.\
"""


def _resolve_save_path(cfg: FrankiConfig) -> Path:
    """
    Return a writable directory. Tries the configured export path first,
    mkdir-p's if needed, silently falls back to cwd on any error.
    Never blocks.
    """
    configured = Path(cfg.export_path).expanduser()
    try:
        configured.mkdir(parents=True, exist_ok=True)
        return configured
    except Exception:
        return Path.cwd()


def run_report(cfg: FrankiConfig, session: "Session") -> None:
    console = Console(highlight=False)

    if not session.history_display():
        console.print(Text("  no conversation to report on.", style=TEXT_DIM))
        return

    skill_map = {
        "pentest": (_PENTEST_SYS, "Penetration Test Report"),
        "soc":     (_SOC_SYS,     "Incident Response Report"),
    }
    sys_prompt, title = skill_map.get(session.skill, (_DEFAULT_SYS, "Session Report"))

    history_text = "\n\n".join(
        f"[{m['role'].upper()}]: {m['content'][:600]}"
        for m in session.history_display()
    )
    messages = [
        {"role": "system", "content": sys_prompt},
        {"role": "user",   "content": f"Generate the report from this session:\n\n{history_text}"},
    ]

    # ── Stream to terminal ────────────────────────────────────────────────────
    console.print()
    console.print(Panel(Text(title, style=f"bold {GOLD}"), border_style=GOLD, padding=(0, 1)))
    console.print(Rule(style=BORDER))
    console.print()

    try:
        full_text = stream_to_terminal(cfg, messages)
    except Exception as exc:
        console.print(Text(f"  error: {exc}", style="red"))
        return

    # ── Auto-save ─────────────────────────────────────────────────────────────
    save_dir = _resolve_save_path(cfg)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    filepath = save_dir / f"franki_report_{timestamp}.md"

    try:
        header = f"# {title}\n\n> Generated by franki on {timestamp}\n\n---\n\n"
        filepath.write_text(header + full_text, encoding="utf-8")
        console.print(Rule(style=BORDER))
        console.print(Text(f"  report saved → {filepath}", style=GOLD))
    except Exception as exc:
        console.print(Text(f"  could not save report: {exc}", style="red"))

    console.print()
